### PR TITLE
fixed levels and add linked-block turorial

### PR DESCRIPTION
**Pull request by RuohanLu**
made changes on formal levels
substitute metal blocks into prefabs
added side cameras for levels
fixed jump issues in tutorial level
based on alpha-hotfix-develop branch
changed one parameter in original powerblocks.cs
Added powerblockslevel script sepcially for one-way&level push in linked-blocks tutorial
merged alpha-fix-powerblocks

### CODE REVIEW

**Comment by edwardsues** [comment]
can we change it so that the camera only shows up when you come into contact with a metal object?

**Comment by edwardsues** [comment]
also @varun6531 thoughts on changing the angle of the camera? kinda hard to see with it rn

**Comment by edwardsues** [comment]
in `Tutorial` level , change `PlayerController` script values to be the same as `First`

**Comment by edwardsues** [comment]
@RuohanLu spawn the player in the right location for linked block tutorial and first level

**Comment by edwardsues** [comment]
in power block tutorial:
- camera sometimes shows the other room, 
- make the player block move, unfreeze its rotation and remove the link, link should be indicating that they move the same way.

**Comment by varun6531** [comment]
> 

yeah we can change the angle

**Pull request closed without merging**
