### PR TITLE
mainly added three levels 

### PR DESCRIPTION
**Pull request by RuohanLu**
made changes on formal levels
substitute metal blocks into prefabs
added side cameras for levels
fixed jump issues in tutorial level
based on alpha-hotfix-develop branch
changed one parameter in original powerblocks.cs
Added powerblockslevel script sepcially for one-way&level push in linked-blocks tutorial
merged alpha-fix-powerblocks

### CODE REVIEW

**Review by varun6531 — APPROVED** [review]
lgtm

**Comment by edwardsues** [comment]
@RuohanLu for the second stage in `Tutorial` , can we raise the block so the player can only jump on it from the upper platform?

image

**Comment by edwardsues** [comment]
in the colliders of all the grounds, can you change them to have `None` as the material like so: 
image

**Comment by edwardsues** [comment]
in level 2 of linked block tutorial, if its possible, can you amke it so that the camera shows up even if you're closer to the door, right now if you're near the entering door it doesn't show up at all

**Comment by edwardsues** [comment]
still need to change spawn location of player in `First Duplicate` level

**Comment by RuohanLu** [comment]
> still need to change spawn location of player in `First Duplicate` level

**Comment by edwardsues** [comment]
your scenes are very weird, which one is the correct version?
 In the duplicate first level: 
 - the camera doesn't show up unless the player is pushing / pulling 
 - they spawn in the wrong location
 in the first level:
 - they spawn in the correct location
 - the camera shows up on push / pull **input** even if the player isn't moving a block

**Comment by edwardsues** [comment]
image

this wall needs to be a bit higher, the player can just jump over it

**Review by edwardsues — APPROVED** [review]
bruh

**Pull request merged**
