### PR TITLE
Renewed main menu

### PR DESCRIPTION
**Pull request by RuohanLu**
- Changed Main menu background, now it is an infinite scene
- Added volume adjuster, through adjusting vMasterVolume of MainAudioMixer
P.S. if new sfx added, please output through MainAudioMixer so that all volume can be adjusted
When choose AudioSourse.output, choose Music if it is music, choose SFX if it is sound fx
image
for sound play in code, add following codes
1 using UnityEngine.Audio;
2 [SerializeField] AudioMixerGroup audioMixer;(choose music or SFX in inspector, please do not choose Master)
3 [AudioSource].outputAudioMixerGroup = audioMixer;

### CODE REVIEW

**Review by edwardsues — CHANGES_REQUESTED** [review]
- why is there a 0 and also a muted option on the volume sliders?
image

image
- volume seems like its TOO quiet once its at <20, is there a way to change the values?
- slider settings still don't persist through scenes, did you not apply the current sfx / music to the mixer? if not, then that might fix it?
- volume sliders still reset when going back to menu, fix this as well

**Review by edwardsues — CHANGES_REQUESTED** [review]
image

everything else lgtm, fix this null ref exception pls

**Review by edwardsues — APPROVED** [review]
lgtm

**Review by Sameer1223 — APPROVED** [review]
LGTM

**Pull request merged**
